### ISSUE TITLE
replace tagName with fieldType

### ISSUE THREAD

**Issue by ayaankhan98** [ayaankhan98/forms.js#2]
right now to write a json file based on which HTML tags are created we have a key named `tagName` in the json file which tells weather the field is of `input` type or it is of `select` type etc etc.

so the task is to change the `forms.js` in such a way that the user no more needs to use the key `tagName` instead the user should be use a key named `fieldType`, i think this word looks more user friendly and makes more sense than the key `tagName`

see `main.js` to have a look at the sample json file based on which the forms are dynamically generated
file needed to be modified to do the task is `forms.js`

**Comment by Zaidtech** [comment]
@ayaankhan98 
 Can I take this issue !!

**Comment by ayaankhan98** [comment]
this repository is no longer of use, so just don't waste you time in this @Zaidtech  if you would like to do something for practice you can take a look at this

https://github.com/ayaankhan98/Flack

flack is a online messaging platform, we can extend this to further level by maintaing this instead of wasting time in this issue
